### PR TITLE
Fixed multi-request batches; Client now submits batches

### LINKED ISSUE #6: Split batches with replace_all will delete all populators not mentioned
There's nothing tying the batch parts together. The protocol is that the first part's response has a GUID that should be included in every subsequent part. If a batch is never completed, `replace_all` will never fire. The last batch will look like a self-contained batch since it's marked as `complete=true`, so all populators for that field will be deleted if not mentioned in that last part.

### PR DESCRIPTION
**Pull request by wblakecaldwell**
Fixes #6 

Multi-request batches need subsequent requests to include the GUID that
was returned from prior server responses. To implement that,
EncodeTagBatchPart has been deprecated, and the client now submits
the request batches and interprets the server response.

Details:
This client doesn't properly handle multi-HTTP-request batches. The server responds with a GUID. When you have multiple parts, the second-Nth parts each need to include the batch guid to tell the server that they're all part of the same logical batch. That's what I added here.

I had to change the gohippo client signature to support this. Before, it would return an array of `[]byte` - one record per serialized batch part. Well, we can't pre-serialize all the requests now, b/c we need to update the 2nd-Nth after receiving the 1st respond. So, I updated the client to actually submit the requests for the caller, and return an object that tells you how much it was able to accomplish.

### CODE REVIEW

**Comment by michaeljho** [comment]
🦛

File: hippo_test.go [hunk 1]
```diff
@@ -1,90 +1,367 @@
...
+		},
+		TTLMinutes: 0,
 	}
 
-	bAllNew, numUp, err := c.EncodeTagBatchPart(r)
-	assert.NoError(t, err)
+	url := fmt.Sprintf("%s/kentik/server/url", ts.URL)
+	response, err := sut.SendBatch(context.Background(), url, &batch)
+	a.NoError(err)
+	a.NotNil(response)
```
[the remark this answers is not in the document]
Comment (wblakecaldwell) [reply hippo_test.go:205]: I don't think I've used require before. Just updated the tests to use it. Good call, thanks.

As far as creating the assert per test - that was just to avoid having to pass `t` in everywhere, that's all. This didn't come from a style guide or anything :)

[the remark this answers is not in the document]
Comment (alistairking) [reply hippo_test.go:205]: I love you! It's always irritated me a little that these kinds of failures would blow things up (obviously not enough to do anything about it though...)

File: hippo.go [hunk 2]
```diff
@@ -126,80 +143,128 @@ func (c *Client) Do(ctx context.Context, req *http.Request) ([]byte, error) {
 	return buf, nil
 }
 
-func (c *Client) EncodeTagBatchPart(rFull *TagBatchPart) ([][]byte, int, error) {
+// SendBatchPart sends a batch to the server, in multiple requests, if necessary.
+// - may return non-nil SendBatchResponse on error, it'll report how far we got
```
Comment (alistairking) [inline hippo.go:147]: do you mean `SendBatchResult`?

Comment (wblakecaldwell) [reply hippo.go]: https://github.com/kentik/gohippo/pull/9/commits/392dd6fa99eb7fbfca436c07f6f8dce57f01f90e#diff-6de703128b8cdd5f7cf717b969ac848cdb6220e788e80ca80e52f6e6ad47dba7

👍

File: hippo.go [hunk 3]
```diff
@@ -126,80 +143,128 @@ func (c *Client) Do(ctx context.Context, req *http.Request) ([]byte, error) {
...
-		} else {
-			reqArrary[i] = next
-		}
 		lastUp += upsertPerPart
-		numUpserts += len(rTmp.Upserts)
 	}
 
 	// Last one has to be handled seperately
-	rLast := &TagBatchPart{
+	ret[parts-1] = TagBatchPart{
```
Comment (alistairking) [inline hippo.go:254]: Minor: can you do this with something like
```
IsComplete: (i == parts-1),
```
But then I guess the code to special-case the slicing gets awkward.

**Review by alistairking — APPROVED** [review]
LGTM

File: hippo.go [hunk 4]
```diff
@@ -126,80 +143,128 @@ func (c *Client) Do(ctx context.Context, req *http.Request) ([]byte, error) {
 	return buf, nil
 }
 
-func (c *Client) EncodeTagBatchPart(rFull *TagBatchPart) ([][]byte, int, error) {
+// SendBatchPart sends a batch to the server, in multiple requests, if necessary.
```
Comment (aaronfuj) [inline hippo.go:146]: nit: docs reference `SendBatchPart` rather than `SendBatch`

File: hippo.go [hunk 5]
```diff
@@ -126,80 +143,128 @@ func (c *Client) Do(ctx context.Context, req *http.Request) ([]byte, error) {
...
-		return [][]byte{init}, len(rFull.Upserts), nil
+		return nil, err
+	}
+
+	outgoingRequestSize := c.OutgoingRequestSize
+	if outgoingRequestSize <= 0 {
+		outgoingRequestSize = DEFAULT_MAX_HIPPO_SIZE
+	}
+
+	if len(serializedBytes) < outgoingRequestSize {
```
Comment (aaronfuj) [inline hippo.go:231]: Should we change this from `<` to `<=` to match the maximum size? This way we avoid the 2 parts, where the second part would be empty...

File: hippo.go [hunk 6]
```diff
@@ -126,80 +143,128 @@ func (c *Client) Do(ctx context.Context, req *http.Request) ([]byte, error) {
...
+
+		if i == 0 {
+			// first response returns the batch GUID, which we need to include in subsequent batches
+			apiResponse := APIServerResponse{}
+			if err := json.Unmarshal(responseBytes, &apiResponse); err != nil {
+				return ret, fmt.Errorf("Error unmarshalling API batch response - [%s] - underlying error: %s", ret, err)
+			}
+			if apiResponse.GUID == "" {
+				return ret, fmt.Errorf("API response did not include a GUID for subsequent batches - [%s] - underlying error: %s", ret, apiResponse.Error)
+			}
```
Comment (aaronfuj) [inline hippo.go:195]: Should we do any additional logging/handling if the `apiResponse` contains an error? May be useful to somehow identify/know that part of the operation had failed for this client(on the server's side) if sending in multiple batches.

File: hippo.go (hunk 3 above)
Comment (wblakecaldwell) [reply hippo.go:254]: yeah - good call though

Comment (aaronfuj) [inline hippo.go:254]: nit: line above spelling/typo error on `seperately` instead of `separately`

**Review by aaronfuj — COMMENTED** [review]
Looks good, had a question around max hippo size (`<` vs `<=`) and the client handling/propagating errors from the server.

File: hippo.go (hunk 5 above)
Comment (wblakecaldwell) [reply hippo.go:231]: I'd be happy to, but it wouldn't be. If it decides it needs 2 parts, it'll split the upserts between the batches:
https://github.com/kentik/gohippo/blob/392dd6fa99eb7fbfca436c07f6f8dce57f01f90e/hippo.go#L236-L237

Comment (aaronfuj) [reply hippo.go:231]: Sure, I was thinking more along the general aspect of thinking that 'max' means the maximum possible, inclusive, rather than exclusive.

File: hippo.go (hunk 6 above)
Comment (wblakecaldwell) [reply hippo.go:198]: I just updated to handle when `Error` isn't empty string, and updated the returned error to have more context:
https://github.com/kentik/gohippo/blob/e124df8e793b6d063cd41ef7151105db19f393aa/hippo.go#L193-L198

https://github.com/kentik/gohippo/commit/e124df8e793b6d063cd41ef7151105db19f393aa

Note: these conditions won't actually be reached today, since any time it's not a success, the status code isn't 200. When that's the case, this is the error: https://github.com/kentik/gohippo/blob/e124df8e793b6d063cd41ef7151105db19f393aa/hippo.go#L184
which looks like this
https://github.com/kentik/gohippo/blob/e124df8e793b6d063cd41ef7151105db19f393aa/hippo_test.go#L502

That error message will contain the full server response, which will likely be that same JSON.

File: hippo.go (hunk 3 above)
Comment (wblakecaldwell) [reply hippo.go:257]: pretty sure you're wrong, but i changed it anyway

File: hippo.go (hunk 4 above)
Comment (wblakecaldwell) [reply hippo.go]: fixed

**Review by aaronfuj — APPROVED** [review]
lgtm!
